# Generated by Django 4.2.6 on 2023-10-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=50)),
                ('credly', models.CharField(max_length=300)),
            ],
        ),
    ]
